apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info
  labels:
    app: movie-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info
  template:
    metadata:
      labels:
        app: movie-info
    spec:
      containers:
      - name: movie-info
        image: 'gcr.io/favorable-iris-266409/movie-info:e2'
        env:
        - name: PROFILE
          value: cloud
        - name: api_key
          value: '1234567890'
        - name: api_url
          value: http://http-mock.mocklab.io/v2/
        ports:
        - containerPort: 8080
