apiVersion: v1
kind: Service
metadata:
  name: movie-info-e2
  labels:
    name: movie-info
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: movie-info
  type: LoadBalancer
